version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb

    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "ac:2c:6b:1c:fa:01:a5:9e:ad:27:bb:d9:37:d5:a1:c0"

      - run: |
          javadoc -Xdoclint:none -d /home/circleci/repo/docs -sourcepath /home/circleci/repo/app/src/main/java -subpackages com --ignore-source-errors -quiet -Xmaxwarns 1 -Xmaxerrs 1
          git add *
          git config user.name "CircleCI"
          git config user.email "CircleCI@ci.com"
          git commit -m "[skip ci] Update javadoc"
          git push --set-upstream origin docs
